### ISSUE TITLE
Dismiss Alerts after 10 seconds 

### ISSUE THREAD

**Issue by harsh-jindal** [dsciitpatna/sahaayak#103]
**Describe the bug**
Currently once an alert if opened it does not dismiss.

**Expected behavior**
Alert shall be dismissed after 10seconds.
**Screenshots**
![Screenshot 2019-05-23 at 11 51 01 PM](https://user-images.githubusercontent.com/31013104/58276678-ac03e600-7db5-11e9-892e-ad354a898720.png)

**Additional context**
Are you working on this?
Someone take this up.

**Comment by Subhang23** [comment]
I am working on this

**Comment by harsh-jindal** [comment]
@Subhang23 Are you working on this?

**Comment by Subhang23** [comment]
Can I use 'Notifications' instead of 'Alert'

**Comment by harsh-jindal** [comment]
@Subhang23 Sure go ahead

**Comment by harsh-jindal** [comment]
@ashwaniYDV Go head on this if @Subhang23 has not made any progress on it.
