### ISSUE TITLE
Sidebar should contain all the categories and clicking on it should give the services

### ISSUE THREAD

**Issue by ashwaniYDV** [dsciitpatna/sahaayak#106]
When user clicks on Milkman button of sidebar this conponent will open which will show all the milkmans.
![a](https://user-images.githubusercontent.com/43786728/58283523-1a50a480-7dc6-11e9-9d8e-541d94eed225.jpeg)

![c](https://user-images.githubusercontent.com/43786728/58283535-25a3d000-7dc6-11e9-8f9a-badca9b679a8.jpeg)

**Comment by harsh-jindal** [comment]
@ashwaniYDV @ritwizsinha Is already working on this.
Please close this issue

**Comment by ashwaniYDV** [comment]
@harsh-jindal @ritwizsinha is working on /services/vendor/:vendorId
I'm working on /services/categoryName/:categoryName and admin portal
