### ISSUE TITLE
Implement user rating 

### ISSUE THREAD

**Issue by ritwizsinha** [dsciitpatna/sahaayak#127]
**Is your feature request related to a problem? Please describe.**
Currently the user cannot rate the services implement it such that userr can rate

Take the idea of implementation from the susi_skills_cms repo

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Are you working on this?
Working on this

**Comment by ritwizsinha** [comment]
working on this

**Comment by harsh-jindal** [comment]
@ritwizsinha I have updated the services page. Please go ahead and add this on services page. 
Start after #151 is merged.

**Comment by ritwizsinha** [comment]
okay
