### ISSUE TITLE
Add loader in register button too

### ISSUE THREAD

**Issue by ashwaniYDV** [dsciitpatna/sahaayak#136]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Are you working on this?

**Comment by harsh-jindal** [comment]
@ashwaniYDV This is a bug. Please open issues wisely according to which are bug and which are feature request.
Also fill the issue template. You have not even mentioned you will be working on this.
