### ISSUE TITLE
Find a good template for a particular service

### ISSUE THREAD

**Issue by ashwaniYDV** [dsciitpatna/sahaayak#138]
**Is your feature request related to a problem? Please describe.**
When a user clicks on more details all the minor and major details of service should be displayed .

**Additional context**
Are you working on this?
Yes

## Current Status
![sr1](https://user-images.githubusercontent.com/43786728/58593555-d90a3a00-8288-11e9-866e-f65f659f8abc.png)
![sr2](https://user-images.githubusercontent.com/43786728/58593557-d9a2d080-8288-11e9-9931-53e0d1567561.png)

**Comment by ashwaniYDV** [comment]
@harsh-jindal Need more suggestions from you about UI.
I have set two tabs at the top of the card for service and vendor details.
In the vendor tab, we can show other services of that vendor and other details.

**Comment by harsh-jindal** [comment]
@ashwaniYDV This looks okay but it doesn't display most important info like address phone number etc..
Will attach screenshots for reference here in sometime

**Comment by harsh-jindal** [comment]
@ashwaniYDV I expect you also to search for suitable template and attach screenshot here
