### ISSUE TITLE
Unhandled Rejection 

### ISSUE THREAD

**Issue by Hardik-Agrawal** [dsciitpatna/sahaayak#143]
**Describe the bug**
On opening Plumber section it is showing an error going back or switching to another service is not possible

**To Reproduce**
1. Go to 'Plumber section'

**Expected behavior**
Some error message and ability to go back or switch to other services

**Screenshots**
![Capture](https://user-images.githubusercontent.com/43006581/58853217-13277180-86b7-11e9-9148-371f666e8077.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 
**Additional context**
Are you working on this?
No

**Comment by ashwaniYDV** [comment]
@Hardik-Agrawal close this issue.
It was due to somebody has deleted the vendor who created this plumber service.
So I've deleted that service.
Issue solved
