### ISSUE TITLE
Enhance UI of Profile Page

### ISSUE THREAD

**Issue by harsh-jindal** [dsciitpatna/sahaayak#21]

**Comment by Subhang23** [comment]
Can you please mention what fields need to be mentioned?

**Comment by harsh-jindal** [comment]
@Subhang23 
Some points to be noted : 
1. Add a h1 tag saying Profile then a horizontal rule below it.
2. Add type="primary" in the update button.
3. Check whether we can increase the size of the photo upload. If Yes then Increase it.
