### ISSUE TITLE
Improve Dropdown UI and Add User Profile to Dropdown

### ISSUE THREAD

**Issue by harsh-jindal** [dsciitpatna/sahaayak#34]
Make it similar to this : 
![Screenshot 2019-04-02 at 2 05 29 AM](https://user-images.githubusercontent.com/31013104/55357926-d3dc7900-54eb-11e9-9a9c-2ac7bb16e111.png)
Use Ant Design Avatar.
@ritwizsinha I don't think Sub menu is required in dropdown just menu shall work. Look into it once.
Add hover (light shade of same colour).
Change the icon to menu icon(3 dots) other than settings icon.

**Comment by ritwizsinha** [comment]
working on it

**Comment by ritwizsinha** [comment]
I think submenu will be useful when if we wanted to add any more icon to the navbar

**Comment by ritwizsinha** [comment]
![image](https://user-images.githubusercontent.com/43509699/55423162-fd081280-559a-11e9-892c-b394ab776b5d.png)
This was the change
I am not able to change css of compoenents effectively , when i read about it ,it referred to some change in less variables and webpack, hence I am not able to center the user icon

**Comment by harsh-jindal** [comment]
@ritwizsinha Refer this https://2x.ant.design/components/dropdown/#. Implement the hover me click menu item. Implement a menu. Sub menu inside the menu is not required. Icon on navbar will not change. And Instead of changing css , pass the username as props to DropdownMenu Component and use it there.

**Comment by ritwizsinha** [comment]
![image](https://user-images.githubusercontent.com/43509699/55473534-916e8580-562c-11e9-8555-87b399f4a5ed.png)

**Comment by ritwizsinha** [comment]
![image](https://user-images.githubusercontent.com/43509699/55473584-ac40fa00-562c-11e9-9388-d2ad47804635.png)
