### ISSUE TITLE
Create Vendor Profession/Sale Page

### ISSUE THREAD

**Issue by harsh-jindal** [dsciitpatna/sahaayak#37]
This page shall contain Name of the shop/business, Address if applicable, phone number, commercial email ID, website link, Hours of operation. Modes of Payment, Year established, Location and Overview, Products and Services offered, Rates of Services provided(optional). 
There will be two part of this : 
1) For owners with shop.
2) Owners without shop.

**Comment by ritwizsinha** [comment]
Working on it
