### ISSUE TITLE
Fix the UI of List your vendor page

### ISSUE THREAD

**Issue by harsh-jindal** [dsciitpatna/sahaayak#90]
**Describe the bug**
Currently the page doesn't show a success alert on successfully registering the business. 
"Enter your details" button should be renamed to "List your business" and button color should be primary not error.
Change the hardcoded country code to select dropdown showing each countries name an code beside it. 

**To Reproduce**
1. Go to 'List your business'.
3. Try registering a business.

**Expected behavior**
All the above points shall be fixed.
**Screenshots**
![Screenshot 2019-05-23 at 1 02 44 PM](https://user-images.githubusercontent.com/31013104/58234283-cc9f5200-7d5b-11e9-8399-ab28192eeb65.png)

**Additional context**
@ritwizsinha Take this up.

**Comment by harsh-jindal** [comment]
@ritwizsinha Create a issue on the server to take in more details for list your business page.

**Comment by ritwizsinha** [comment]
working on it
