### ISSUE TITLE
Fix Home Page in Mobile View

### ISSUE THREAD

**Issue by harsh-jindal** [dsciitpatna/sahaayak#91]
**Describe the bug**
Currently the home page in mobile view is not good.
**To Reproduce**
1. Go to 'Home page'
2. Change to mobile view from console

**Expected behavior**
Make the sidebar and slideshow similar to [Flipkart](https://www.flipkart.com/ ) in mobile view.
**Screenshots**
![Screenshot 2019-05-23 at 1 12 46 PM](https://user-images.githubusercontent.com/31013104/58234565-7a126580-7d5c-11e9-942a-ea6779de93d5.png)

**Additional context**
@ashwaniYDV Take this up.

**Comment by ashwaniYDV** [comment]
@harsh-jindal WIP
